<?php

$general_cards = array(
	"fool" => "The Fool - The Fool keywords are innocence and ignorance. It is both a good card and a cautionary tale. The card depicts a donkey that has eaten an apple containing a razor blade. This typically speaks to times when we are more likely to act without thinking of the consequences, which ends up landing us in hot water. So that can be an issue. But aside from that danger, it also represents a sense of childlike innocence. The happy-go-lucky person who seems to just enjoy life in a way that other people may be too afraid to do or have forgotten how. The ignorance part of the equation simply speaks about not having enough experience about a certain thing to recognize any of the dangers that may be present, but it could also mean not recognizing an opportunity when one presents itself. So this card shows two sides of the same coin. This card could also come at a time when you need to stop overthinking something and just have fun with it. In other words, dance like nobody's watching. <br><br>",  

	"magician" => "The Magician - The Magician is all about skill and talent. As if by magic, he seemingly makes things happen out of thin air. Anything he wants seems to be right at his fingertips. The picture shows one card of each suit in his hand. He's got all the power of all the suits at his beck and call, but the thing is, it comes from within. He's not really magical. Just like all magicians in real life, it's all just an illusion. But the skill and the talent, that's real. With enough practice and with enough drive, anything is possible. The magician realizes this. It's not magical at all. It's work and perseverance. All he does is visualize what he wants, then he figures out how to get it. The real thing that makes the Magician so powerful is the mojo of knowing that anything is possible. He believes in himself and his abilities, so there is no reason for failure. <br><br>",  

	"high priestess" => "High Priestess - The High Priestess deals with intuition and mystery. So here we have an external influence that seems to be secretive, maybe not telling you everything that's going on. This could also point to you needing to trust your gut more rather than the emotional stimulus that kind of clouds judgment sometimes. Being able to see through the fog will help you make better decisions in all aspects here. It also could mean that you are seeing the issue as sort of a mystery, but still a mystery that can be unlocked. Uncovering the mystery behind anything that worries you will help you advance and make lots of progress where this is concerned. Learn about what confuses you and take away its power. It will help to be aware of potential pitfalls so you can work on not doing them. This plays into that aspect of going with your gut. The more experience you have with something, the better your gut will be at warning you. There is no reason to just dive into everything and hope you come out the other side. Find a map. Life is only a mystery until you start seeking answers to questions. <br><br>", 

	"empress" => "The Empress - The Empress depicts a pregnant woman holding her other, already born child. Notice how the baby is still alive. Because she didn't kill it or anything. The keywords here are nurturing and natural. She is very down to earth. This card hints at nurturing the things you care about to help them grow. You have to be there for the things you love or they will be neglected and probably die. Like if you have a pet rabbit that you never feed, it will just end up starving to death and you will no longer have a pet rabbit. Some people don't know that. So see your things through to completion. The other side of this is that at times you have to be able to let those things of yours breathe and learn and live. If you smother something, it cannot thrive adequately, which is basically the same thing as strangling it with a shoestring or something similar. <br><br>", 

	"emperor" => "The Emperor - The Emperor is about authority and structure. This is something that is sorely needed at this point in time. The idea is that if you're not able to take responsibility or control, you should delegate that task to someone you know will hold you accountable. Someone like an Indian chief. Because Indian Chiefs are awesome and there's no one who can say different without being a filthy liar. You need someone who is able to think things through and who will be tough on you when you need it. Because you're not being tough enough on yourself. So you need someone else who can be. You're letting your mind convince you of things and then you're making excuses and coming up with ways of convincing yourself it's okay. It's called justification. Sometimes it's legit and other times it's not. You need someone in your life who can tell you when you're lying to yourself. And again, this could be you, but it's hard to do this for ourselves. So in other words, you need to start being a leader and assume control of your life and your situation or else someone else will. Do you like it when other people dictate the circumstances of your life? No? So do it for yourself or someone else will. <br><br>",

	"hierophant" => "The Hierophant - The Hierophant is about convention and tradition. Societal structure that's designed to maintain the status quo. The Hierophant is typically reminiscent of religious or academic institutions, but it goes beyond that and covers basic cultural and social norms. Mostly it refers to all the crap that's designed to keep people in line. The powers that be. The turds in control. It's a double edged sword, having people dictate how things should be. The theme of this card is very much coloring inside the lines, or at least seeking out that which is tried and true. There is a time and place for going against the grain, and doing your own thing - even being rebellious - is something that shouldn't be discouraged. But this card seems to be about traditional knowledge, going with the flow, following the rules. It certainly helps make things run smoother, so this might be an instance where you should just play along with something to avoid making waves. You can always be dissenting later on. <br><br>",

	"lovers" => "The Lovers - The Lovers is typically one of the most favored cards for people to get, because most people for some reason wish for fairy tale romance more than any other thing. Never mind the fact that they can develop themselves to being the person who is not only worthy of getting what they want, but capable of going after the type of person they want without having to settle. Most people are lazy, and they just expect the universe or fate to drop the perfect person into their laps willy nilly. The Lovers isn't about getting that person handed to you on a silver platter. It's about the expanded potential for meeting or rekindling that romantic atmosphere that most of us end up either taking for granted or blowing anyways. So utilize the opportunity and give yourself better odds by not being irresponsible when it comes to relationships. Improve yourself, respect yourself. Those two things will help you land who you want. Don't be lazy. <br><br>", 

	"chariot" => "The Chariot - The Chariot symbolizes victory and will power. This means the victory is brought about by you seizing control of the situation and making it do what you want. There's an Impala shown on this card. So your situation needs to be driven like a car. Get behind the wheel and make the car do what you want it to. It can go as fast or as slow as you want. Another good thing is that like cars, you can bring along passengers. So in essence, your victory can benefit a lot of other people. This card points to sure success. The thing you can't allow, though, is the situation to dictate what happens. Don't let the car control you. Don't be afraid of whatever you're going through. It'll only make things worse. Just like driving a car. The car is under your command. It will respond the same way whether you are confident or scared, except when you are nervous, you will make mistakes. This is not the car's fault. Take control. <br><br>",

	"fortitude" => "Fortitude - Fortitude shows a woman getting a tattoo that says, 'Nil desperandum' which is 'never despair' in Latin. This is about inner strength, and this card usually appears during times of emotional upheaval or turmoil. It's about perseverance in the face of adversity. Think about the tattoo symbolism here. A tattoo is not like getting a band-aid ripped off. They take a while, so you have to sit through it. But the important thing to remember is that it doesn't last, and usually if you make it through, there are great things waiting on the other side. With a tattoo, it's easy to put your mind on the end result. With life, this is more difficult, but never despair. Instead of thinking about that cool tattoo, think back on troubling times before you've made it through, and you'll see that this is no different. Life never gives us anything we can't handle, and coming out on top through a harrowing experience enhances our character and makes it easier the next time. Provided that you don't forget the previous experiences. So do not despair. You've made it through everything else. You will again. <br><br>",

	"hermit" => "The Hermit - The Hermit shows an old man with a beard and a pipe. He is pretty awesome. His identity is kind of shadowed. He's an iconic symbol of solitude and self-exploration. No one knows much about him because he keeps to himself. Some people might even think he's a jerk, but that's only because they haven't talked to him. It's kind of an apt card for someone who is struggling with a lot of questions. Know thyself. It is said that humans have a unique ability to not know nothing at all about themselves, so this card is saying you need to reflect about you. What are some things you might not want to face up to? What are some things about yourself that you might not want to admit? Now is the time to figure that out, so you can get past it. Know what your flaws are, admit them, then surpass them. Also, know what your strengths are and embrace them.  The Hermit can be that cantankerous old codger who doesn't like people, so he keeps to himself. There will be a bit of heat at first until you find your way, but your desire to do this will help you through it. Seek the answers within, you will find that you know more than you thought. <br><br>",

	"wheel of fortune" => "Wheel of Fortune - The Wheel of Fortune is always tricky. It implies things like luck and destiny and fate will either deal you a good hand or a bad one. Sure, it goes up and down, round and round, but this is as good a time as any to do what you want. Why? Because if you wait around for conditions to be right, you will NEVER do it. Ever. Fortune favors the bold. Do it. Make your own destiny. There is no such thing as a bad idea, only a poorly executed one. If you need proof, just look at the popular garbage on the internet. There's some dumb stuff on there that is extremely popular. If they would have asked people first everyone would have said not to do it because it sounds dumb. But they did it anyway and now look at them. There are 7 Billion people in the world, most of which are connected now online. SOMEONE out there will buy into what you're doing or be excited about your idea. So don't wait around for the right time or for good luck. Luck has nothing to do with destiny. Make your own destiny. We all have ups and downs, but we don't all follow our dreams. <br><br>",

	"justice" => "Justice - Justice is the ability to weigh issues fairly, with reason and understanding. This also means affording to other people their rights, regardless of if you agree with the specifics of those rights. Knowing when you are being unreasonable and making an adjustment. Being fair to others, but also yourself. This suggests weighing the pros and cons heavily and trying to look at all angles of the scenario, all the evidence, and of course, not rushing to judgment. So being able to make a sound decision that's fair for you. It also suggests that you will get what you deserve, no matter what, which can be a double-edged sword. In other words, you will reap what you sow here. Please note that justice does not mean 'punishment', though punishment could be the result of justice. Justice is about treating everyone fairly, without bias, even if you don't like them or if they belong to a different religion or political party or have different ideas. Justice is blind. Justice is balanced. <br><br>",

	"hanged man" => "The Hanged Man - The Hanged Man is about seeing things from a different point of view or perspective. Taking a step back, holding your horses and being patient. Not letting your cool come unglued without good reason. The keywords are 'pause' and 'reversal.' The card pictures a gymnast on the still rings holding a difficult position upside down: the inverted cross. It's hard to do, but he gets higher points the longer he holds it and even more if he can do it completely still. Remember that our view of the world is only limited to what we've experienced already. Imagine a completely darkened room. You have a flashlight in your hand and you are exploring that room. Everything in your world is what you've seen. Imagine that another person is in there with you, looking at other things in the room. Their world is different. Some of the things they've seen are the same as you. Their flashlight might cast a wider swath of light than yours. This just means it may take you longer to see what they see. Some people never try to expand their world. There are two sayings I'd like to share: 'The fish thinks it knows what's best for the crow.' This means what's in your world might not be ideal for others. Or even for yourself. The Hanged Man is about capsizing your paradigm. You'll see things like the Matrix. The second thing: 'How can I know if I am wrong if no one tells me?' Think about that one. <br><br>",

	"death" => "Death - Death is all about personal change. Improving yourself every day. In essence, it signifies the death of your old self. Remember that if you keep doing the same things you'll keep getting the same results. You gotta improve something, tweak something. And this doesn't just apply to the work process, it more than anything applies to yourself. So many people spend their whole lives without ever trying to improve themselves. They refuse. Outright. We'll use a relationship as an example, because everyone understands this way. Imagine a person who always says 'So-and-so should love me for who I am.' That's only part true. And kind of selfish. Or they wait and wait and wait for someone to pick them. So the optimal plan in that situation is to improve one's self. In all aspects. Work out. Dress better. Become better at conversation. Improve your self-esteem. Etc. etc. The idea is to give other people your best self, and more than that, to give YOU your best self. It'll also increase your options, which is important there. So how does that concept also apply to other areas? What can you do to improve? <br><br>",

	"temperance" => "Temperance - Temperance is where you need to be. This is completely internal, as in you have total control over it. And it applies aptly to everything. The keywords here are balance and restraint. You've got to find a good balance between work and play, between going out and staying in. There are extremes - a right and a left - in everything. The middle is a safe place. How this applies here is that you will need to practice the art of self-control. Acting in moderation. Being able to restrain yourself from excess in any form. Tempering yourself to avoid overcorrection, which leads to the pendulum effect. Being balanced. It is considered one of the four Cardinal Virtues because it is believed that no virtue could be sustained in the face of inability to control oneself, if the virtue was opposed to some desire. All vices are overcome with Temperance, which makes this such an important virtue to embody. Self-control is the only way to keep our demons in check. Another component of temperance could also be patience. <br><br>",

	"devil" => "The Devil - The Devil signifies obsession or being locked into something that you feel you are beholden to. And this could be anything. The standard answers that people usually go with are drugs, alcohol, sex, gambling, etc. But it could be anything that you have allowed to sink its teeth into you and control you. Could it be a person? Or a situation? What is it that you can get out from underneath that is slowly destroying you? Is there something you're absolutely obsessed about that's taking up all your time, energy, or thoughts? The other thing to remember is that this 'devil' is not external. It is inside you, a darker part of you that you have allowed to take command of the ship. It is an inner demon, and the good news is that because you created it, you can destroy it. You have the power to resist it, even though it will try to convince you that you don't. It is very tempting, this demon. This is a figurative demon, by the way. There is no need to visit an exorcist. What have you lost control over? <br><br>",

	"tower" => "The Tower - The Tower is the scariest card for some people - for most people. Because most people hate change. They fear it. Because it's uncomfortable. People don't like having to rearrange something or go to plan B or even make a plan B if they didn't have one. The card features a huge apartment complex, the top floor in flames. The keywords are 'upheaval' and 'sudden change'. That's the rub there, that it's all of a sudden. So something will happen all of a sudden that will cause you to make a few changes. This is as good or as bad as you allow it to be. It may be a pain in the ass, but your mindset is what transforms challenge into an opportunity. 'A pessimist sees the difficulty in every opportunity, an optimist sees the opportunity in every difficulty.' - Winston Churchill. Another key thing to remember is that progress never happens without change. If things remain the same, they will continue to be the same. People find comfort in that. They would rather accept what they have than have to endure some discomfort for even a chance that things will be better. Take the opportunity of the change and find the way things can be better. <br><br>",

	"star" => "The Star - The Star, it basically shows a stripper. It's got a pair of some hot stripper shoes beneath a disco ball. The keywords are 'hope' and 'success.' This card is illustrated in this way because a lot of strippers are in the spotlight, so they're like the star of the show. It's also a throw-back to the naked lady in the pool as seen in other tarot decks. The star card kind of serves as a reminder that there is hope. The stars are always there, whether we can see them or not. You can wish upon a star also. So this is sort of a bright light in the darkness. Maybe there are things we cannot see. When times seem harsh, we fail to notice the bright side of a situation. That's what the star is for. You need to look on the bright side, or see the light ahead. Because it is there. It is always there. You just have to quit focusing on the darkness. <br><br>",

	"moon" => "The Moon - The Moon card represents illusions and fear. Compared to the sun or the stars, the moon is rather mysterious. Because it doesn't produce its own light, it is like a mirror, reflecting the light of the sun, so the moonlight has a kind of ethereal quality, which sort of shows us a different aspect of things. It is like the dream side of things, the otherworldly aspects. This is why it seems as though things are illusory and dreamlike. Seeing things in the moonlight gives them an otherworldly quality, which can lead to fear. Remember in this time that everything is not as it seems, that it's just being cast in a strange light. There is nothing to fear. And pay attention to dreams and your intuition here, because it might be urging you to see something specific. But this is a reminder to see things as they really are and not as they appear to be. <br><br>",

	"sun" => "The Sun - The Sun is about joy and enlightenment. It depicts a big sun and a puppy playing with a kitten. It generally envisions a time of warmth and comfort, like a warm summer day. But more than that it symbolizes bright light that shines upon the darkness, eliminating confusion and showing us the clear path forward. See, this card comes after the Moon and the Star card. The Moon card talks of light that may be confusing and mysterious (moonlight). The Star talks about a light of hope, as if to wish upon a star or navigate by (starlight). The sun is the brightest of these, so when it shines its light upon everything, you will be able to see whatever answer you're looking for. But you have to be open to whatever you find. In other words, it will light the way, but you have to make the journey. So pay attention to what is being shown to you. <br><br>",

	"prudence" => "Prudence - Prudence is the ability to gauge your actions and be able to choose the correct action at the appropriate time. Prudence means having sound judgment, thinking before acting, understanding the consequences of those actions, and knowing how they will affect others. It is one of the four virtues, and it requires that you be reasonable in all areas. It is all about making better decisions and also not being afraid to make decisions. Weigh evidence and options and tailor a strategy accordingly. Think about the people who must act prudently and try to emulate people who are very wise. Use your experience, but also seek out new information and new experiences to enhance your abilities and your proficiency in all areas. The more you know, the better you will be at this. <br><br>",

	"world" => "The World - The World signifies coming full circle through a long journey where you will have learned all the lessons you need to adequately move forward into the next iteration of things. The keywords are synthesis and prosperity. Many times it denotes travel and being cultured, or just knowing a bunch of stuff in general. In all aspects, this card is essentially a 'been around the block a few times' card. You've been around, you've seen things, you've learned things. You know things. You took the time to open up your world to a variety of experiences. You can use this knowledge to hone in and discover what it is that you really want. Most people don't give themselves the room to learn what they don't want. They think they're just going to get it right after a couple tries. You know better. There's so much pressure to get things right in life. To have the fairy tale, to find that one partner, to get the right job, to not have a terrible kid. The World says otherwise. That other stuff is naive. You know what you want, which means you are more likely to get it. If you don't know what you want, you should probably starting thinking about that. Make a decision. Then go for that. <br><br>",

	"badass" => "The Badass - The Badass is an extra card in the Darkana deck because none of the other cards REALLY embody what this card does. The World talks about learning every lesson and acquiring great wisdom. But this card is about self-actualization. Becoming the best version of yourself - the person you've always wanted to be. Doing things on your own terms and focusing more on yourself and how you can be better than focusing on what others think about you. Just think about other badasses and you'll see. Pick someone you admire. Now ask yourself what that person would do or say if people told you certain things. Or do certain things to you. How is your reaction different than that of the badass? Does your ideal badass react to petty things? One great tip is to picture a lion being hassled by a fly. Is the lion scared? Does it even bother? No. It need not concern itself with minutae. The keywords are SMOOTH and AUTONOMOUS. Be your own badass. <br><br>",

	"ace of swords" => "Ace of Swords - The Ace of Swords depicts a chainsaw, because chainsaws are cool. Swords cut stuff and so do chainsaws. So since this card is about ideas and knowledge and things, what's happening is you're going to be getting some of that delicious info into your brain somehow. It's as though someone is just implanting ideas and cool thoughts and brilliant epiphanies right into your noggin. And it will all be stuff you can utilize, too, nothing extraneous. So the right thing to do will be to put those thoughts into action, because swords are also about action as a result of our mindset. A winning attitude is the most important aspect of any endeavor. 'Whether you think you can or you can't, you are right.' - Henry Ford <br><br>",

	"2 of Swords" => "The 2 of Swords is about avoidance, stalemate, and indecision. There's a pair of scissors on it and there's a little toddler holding a time bomb with two wires. Which one do you cut? One way will save the baby and the other will kill him. And you. Or maybe neither wire will blow it up. Maybe it's a trick. This is the type of stuff that goes on in our heads when we can't decide about something. We're too scared to choose something because we think we will mess it up. Every choice may have a lot of pros and cons. It's usually a hard decision, but sometimes it's not really. It's just that people don't like to make decisions. So you have to ask yourself what will happen if you don't make a decision. And what's the worst thing that can happen if you go either way? Be honest here. What's preventing you from making these choices? Either way? Is it just you being indecisive? If so, just choose one and go with it. Run with it. Don't be a bitch. Just choose. If you choose wrong, adjust later. <br><br>",

	"3 of Swords" => "The 3 of Swords shows a voodoo doll with three pins through the heart. What it mostly represents is sorrow and loss, and since the suit of swords is about thoughts, ideas, it is actually a sort of 'clashing' - tribulations and conflict; this is completely something that's within your control. So what this means is that the way you feel in response to any type of loss has a lot to do with your mindset regarding the situation. For example, one might easily get too excited about a new fling too fast and start thinking they are 'the one,' which is an easy way to set themselves up for a big disappointment. This could be because they began from a place of hope and expectation rather than from the mindset of 'I'm going to see if this person is who I want to be with.' Do you see what this is getting at now? Also, some people experience a setback and it takes them forever to get over it because they don't believe they ever will. It hurts too much. But they fail to think back on all the many other times where they felt and thought the same thing. They survived everything else. This is no different. So think about that next time you are saddened. <br><br>",

	"4 of Swords" => "The 4 of Swords shows a team of doctors. The keywords are rest and recovery. How does this apply to your situation? It's saying that you'll have to balance out the hard work with periods of rest. Otherwise you'll get burnt out. You want to avoid that, because it can actually cause you to get jaded about a situation. So you'll have to find ways of breaking away from the routine, to relieve the stress of everything, which can help keep your enthusiasm high. One way to do this is by keeping things fun, so it doesn't seem like work. If you're having fun, it's not work at all. If it gets to be too demanding, take a step back to recuperate, and then get back in the game. Rinse, repeat. The other thing to keep in mind with this card is that because it's the suit of swords, it could also signify thinking way too much about things, especially things that you mind feel like you can't find the answers to. Sometimes the best thing to do is to take your mind off of an issue for a while to allow the answers room to come to you. It's like trying to chase a cat. If you leave the cat alone, it will come to you. <br><br>",

	"5 of Swords" => "The 5 of Swords depicts a ninja attacking a defenseless woman. Ninjas were looked upon as being without honor in Japanese society, but they were also highly misunderstood and at a disadvantage in the culture. The keywords for this card are Self-interest and Dishonor. This card suggests that someone or someones is being sneaky and dishonest, and ninjas are very good at this. It is in their wheelhouse. The way to knock a dishonest person off-balance is to shine light on the truth. Spotlight things. The more you use your mind (swords) and point out evidence, the easier it will be to keep this dishonest person on his or her toes and get to the truth. They'll slip up. It is your job to call them out so they discontinue this activity. <br><br>",

	"6 of Swords" => "The 6 of Swords is about escape and rescue. The Darkana image shows the special operations helicopter used by US Air Force Pararescue. This image was used because this is one of the only helicopters with 6 rotors. At any rate, this card signifies an escape from a less than favorable situation into a better one. Traditional cards show a woman and a child in a boat. This card is a reprieve or a sanctuary. The important thing to remember is not to bring too much baggage along with you to this new place. So whatever this is, you will feel like a huge weight has been lifted from your shoulders. Allow this to happen and don't pack on the unnecessary weight of heavy dwelling on the past. Look to the future so you don't repeat the mistakes of the past and become rooted there. <br><br>",

	"7 of Swords" => "The 7 of Swords shows a shadowy figure standing near seven swords. The keywords are dishonor and retreat. Typically this refers to someone telling you lies. Deception of any kind. Things people don't want you to know. Someone taking advantage. There are lots of different types of manipulation, and it's hard to be aware of all of them. So one of the easiest ways to tell when people are telling you tales is to pay attention only to their actions instead of their words. If their actions don't coincide with what they say, they're lying through their rotten teeth. So pay particular attention to those things. The best way to combat these people is to shine light on the truth, and have evidence especially. Sometimes these turds will try to play the victim, like you're out to get them so they can get pity from everyone else. That's why you need evidence. Don't be afraid to call them out or they will keep viewing you as someone to victimize. <br><br>",

	"7 of Swords Reversed" => "7 of Swords Reversed seems to be that you're getting the whole story from somebody. What you're being told is the truth. Sometimes the truth doesn't sound like the truth, or it's not what we want to hear. The truth is still the truth, whether you believe it or not. So what you're doing is essentially not believing something you're being told because maybe you don't trust it or you don't want to believe it. I once had a friend who constantly thought his wife was fucking someone else. She never was, and she never would have done that, but he always thought she was. So much so that he started hoping he would catch her cheating just so he could say 'I knew it!' Who is telling you the thing you are skeptical of? Are they more qualified than you? Are you being unreasonable? Is it just you reacting to not wanting to hear the news? Think of these things before drawing too many conclusions. And don't act like my friend did, because that's a surefire way to drive someone to do whatever it is you're suspecting them of doing. <br><br>",

	"8 of Swords" => "The 8 of Swords shows a straightjacket pinned to the wall by 8 spikes. The keywords on the bottom are Restriction and Doubt. What the card normally symbolizes is a sort of self-fulfilling prophecy or a self-imposed prison. This is all related to paradigm, or your mindset. Or the way you've been doing stuff. The fact of the matter is that ultimately, success is up to you and whether you choose to accept whatever fate comes your way or whether you decide to forge your own destiny. It can be done, you just have to be willing to put in some effort to try some new things and work hard. So this prison involves you accepting whatever happens, or you can break that cycle by getting involved heavily in your own destiny. Other terms for this are 'stepping over your own feet' or 'fucking yourself in the ass.' <br><br>",

	"9 of Swords" => "On the 9 of Swords we see a baby in a crib under a mobile made from swords. The keywords are worry and guilt. So there are two things there - worrying that the mobile will fall or that the baby will harm itself while playing with the mobile, and the guilt at possibly feeling like the whole thing is your fault, that it could have been prevented, or even something deeper, like feeling guilty about a long string of circumstances that led to one having to place the baby in an environment like that in the first place. There are a couple lessons from this card. The first is that worrying never changes the outcome. While you might be worrying about something that's a possibility, it's still not reality until it becomes actual reality. It's fiction. It's fantasy. It's in your head. A LOT of stress can be avoided when you realize that worrying serves no purpose whatsoever. It doesn't help anything. There are no positives. None. Stop worrying. Do not be worried about things that in all likelihood will never manifest anyway. It becomes a self-fulfilling prophesy. Until it actually happens, it is all a figment of your imagination. <br><br>",

	"10 of Swords" => "The 10 of Swords shows a crime scene chalk outline and 10 swords. This usually kind of shows several things. The first is that 10 is the last card before the courts, so it kind of says, 'this is the end.' So it could be the end of something terrible. The other thing it implies is 'it can't be any worse than this.' The worst has happened already. The dead guy is dead. The keywords for this card are 'victim mentality.' That is the other aspect. The person feels like a victim and continues feeling like one no matter what is happening or has happened. It's like the end of the world all the time. And because the swords are about ideas and knowledge, all of these issues can be issues of the mind and perception. The last thing this card could portend is that something will end very badly. As in, if you go down this path, things will end up like the guy in this card. It will be nasty and it will take a while to recover from this. It's like a warning sign on a wilderness trail that says 'Warning: Entering Bear Country'. Be very prepared. But don't play the victim. <br><br>",

	"Page of Swords" => "The Page of Swords depicts a young boy scout and a Swiss Army Knife. The keywords are 'thought' and 'truthfulness'. This particular character has a strong sense of ingenuity. A bright problem solver, like a young MacGyver. The truthfulness aspect stems from the boy scout depicted. They are trustworthy, brave, loyal, etc. They are well-rounded, and love to learn stuff. Collecting knowledge, if you will. Like merit badges. The key to this person's successful growth is to give him or her room to experiment, especially with thoughts. They need to be allowed to figure things out for themselves instead of being told the answers or what to think. Problem solving is something the Page of Swords enjoys, it becomes a personal challenge. They simply want to see if they can figure stuff out. If they need help with something, it is almost better to point them in the direction of resources that will help them solve their problem rather than to tell them what to do, even if you know the answer. You have to lead them to the answer so that they feel like they have found it themselves. <br><br>",

	"Knight of Swords" => "The Knight of Swords is direct and incisive. Very sharp and brutally honest. Even though he may be too honest for some, his words are usually biting, but they carry truth and wisdom with them if we are strong enough to heed them. So many people who can't handle it will just write him off as a jerk rather than actually listen to the truth he might have to say. This Knight is the type of person who doesn't care about tact, but will tell you what you need to hear. It is our problem that we choose to ignore it simply because it hurts our feelings. What you need now is to be more like this Knight. Don't be afraid to speak your mind. You can use tact, it would be helpful in many situations, but the key is to be intrepid about it. Stand up for yourself and be more assertive. That is the key. Don't be aggressive or people get defensive, don't be passive or people take advantage of you. Be assertive. Assert yourself and you will ween people off the need to take advantage of you. Be smart and calculated with what you say. <br><br>",

	"Queen of Swords" => "The Queen of Swords happens to be the queen of ideas and knowledge, thought, information. She's very reasonable, intuitive. She thinks things through before doing them. She seems cold-hearted sometimes, almost like a judge, but that's only because she makes decisions based on weighing everything through in her mind. She looks at evidence. So, like a judge, she can still deliberate in favor of someone she doesn't like over someone she does like, given the evidence and the circumstances. It's nothing personal. The keywords on this card are Astute and Forthright. She isn't afraid to hurt feelings if she's telling the truth. She can be tactful, but she doesn't sacrifice clarity or being concise for tact. She tells it like it is because it's true. How people react to it is their problem. <br><br>",

	"King of Swords" => "The King of Swords is the master of his domain, which is analytical thought, critical thinking, problem solving, articulation, and reason. This person is likely a great debater, can be very blunt at times, and favors having a cool head and thinking through things instead of flying off the handle like a turd in the wind. He is an excellent communicator and has a way of explaining things so that they make sense. This person could be a teacher, programmer, philosopher, lawyer, or a judge. Because he is more rational than emotional, he may seem very distant at times. He might even have trouble expressing and putting into words his emotions, which he doesn't understand, so it's important when dealing with someone like this to remember that just because they can't express well their feelings, that doesn't mean that they don't have them. You have to learn to go by their actions instead of their words. They will find ways to show you how they feel. If this person is you, try explaining that to other people. If they still don't understand, you may be in a situation where moving on is something to consider. Just use your judgment. If people are too unreasonable, is it so unreasonable for you to not want to be around them? <br><br>",

	"Ace of Wands" => "The Ace of Wands depicts a large quill. The keywords listed on this card are passion and ignition, and it's usually a great card to get, especially when starting a new project. So what's happening is that you'll be getting some of that creative spark everybody hopes for in this area. I like to call this the creativity fairy planting inspiration inside your brain. It's like magic. And sparkly. You've got to obey the muse, though. The way to do this is not to ignore it or try to force something you're not inspired to do. An example is say you want to draw a picture right now of something awesome but you still have a short story you were trying to finish up. If you try to keep working on the story while all you really want to do is draw a picture of a unicorn with flames coming out of it, you'll screw both of them up. If you force the one you're not inspired to do, you will get neither done. Obey the muse. There have also been some interesting studies on creativity that suggest relaxation is the number one facilitator of creativity, as opposed to thinking too much, which inhibits it. So relax. Grab a drink, have a smoke. It'll flow. <br><br>",

	"2 of Wands" => "The 2 of Wands depicts a hand holding a pair of chopsticks and the hand is grabbing the world with the chopsticks, because this hand is supremely awesome. The keywords are boldness and command. This is about taking a chance, being bold, intrepid, fearless. Going where you're afraid to go. Leading the way. Being a pioneer. Do not be afraid to do so, because it is the unknown. The unknown is easy to fear, but is there really a lot to fear? Do you trust those around you? What about others who have taken this bold step? Did some fare well? Remember that going forward. Fear is always fiction. Danger is real, but fear is made up. When you fear something, you're afraid of things that haven't even happened, which makes them fiction. Be brave. Be bold. Fortune favors the bold. Who Dares Wins. No one ever accomplished anything worth a damn by sitting around not taking risks. Progress only happens when we leave our comfort zone. Get out there. To hell with safety. <br><br>",

	"3 of Wands" => "The 3 of Wands depicts a cowboy leaning up against a wooden fence overlooking a vast plain. The keywords are exploration and leadership. So this is about taking charge of your life and leading it into a new direction, or at least the direction you really want it to go. Like the cowboy, you must be in charge of this process. He leads the herd of cattle across thousands of miles of terrain, sometimes into unknown territory, but he always gets them where he needs to go. At no point does he lose control. If he does, they herd will own him. So you must do this with your life. What are your goals? Why haven't you accomplished them? What's the deal really? Are you just making up excuses? What's stopping you? Be the cowboy. Go where you want to go. Own the herd. Own your life. <br><br>",

	"4 of Wands" => "The 4 of Wands shows an old house being held up by four trees. This represents stability and structure. The suit of wands is the suit of fire, which deals with passion and creativity. The thing about this card, too, though, is it deals with a general sense of stability and structure, not just in terms of creativity. So the key here is to look at areas around you and see if you can find areas that need to be fixed. In other words, this card says you should try to get your act together. So what areas are you lacking in that regard? Having structure will free you up in pretty much every other area, so there is less piddly crap to have to deal with, which will come in handy if anything majorly awful or unexpected happens. Instill some structure and stability into your life so you have less stress to deal with. <br><br>",

	"5 of Wands" => "The 5 of Wands depicts four people in a wild west shootout. There are 5 guns being used (five boom sticks). The keywords are quarrel and competition. You will likely be dealing with people who are all about excessive competition in a certain area, so you will have to rely on your talent and skill and ability and use that to not be daunted by anyone else. The other aspect this card could point to is that you may find yourself in the midst of a quarrel or competition and you choose not to participate. To sit this one out. What would end up happening in this instance, though, is that you'll lose automatically. You miss 100% of the shots you don't take. Taking a passive approach won't help you there. You'll have to assert yourself in order to get what you want. Do not be afraid of competition, you have what it takes to come out unscathed. <br><br>",

	"6 of Wands" => "The 6 of Wands describes triumph and acclaim. It pictures a man on a horse carrying a large banner. He is being recognized for his work and his actions, which may have been a long time coming. There are others here who are cheering him on. People who admire him and look up to him. Being on the horse, he is elevated above the others. This is just symbolic. The others genuinely feel good for him because he is victorious. He need not brag about his achievement, there are others at the ready with accolades. But he is also not afraid to put this achievement on display, hence the flag. The flag represents him and what he has accomplished. Another symbol by which people can recognize him from afar. You are about to be recognized for something, so enjoy it. You are about to be victorious. <br><br>",

	"7 of Wands" => "The 7 of Wands is about challenge and aggression. In any Rider-Waite ripoff you'll see a guy fending off a cabal of unseen attackers. Usually this means you need to hold your ground and fight back. Could be jerks at work. What have you. You need to beat them to a pulp with a giant stick. The Darkana deck shows a huge viking ship, because vikings were also known for being turds to people who just wanted to be left alone. It's also hard for a ship to sail upside-down. The Titanic is a good example. Standing up to aggressors takes time and you basically have to have stamina. Same thing here, but you can use a few techniques of your own to disrupt their crap even further or head them off at the pass. There are many ways to fight back, so even 'stooping to their level' isn't your bag, there are other things you can do that will help disrupt the flow of that Viking ship. But don't just sit there and take it or it will never end. <br><br>",

	"8 of Wands" => "In the 8 of Wands we have the archer, poised to loose his arrow into the guts of some unsuspecting victim. 7 more are in the quiver on his back, so he can mess someone's day up if he really wants to. This card represents swiftness and movement. So things are about to start picking up, start being less stagnant. You'll be making some changes, seeing some progress, maybe some things won't work out, but you'll be on your way to awesomer pastures. It's like setting out on a foot journey. You've been walking a while and starting to think that it's not worth it, maybe be dumb and turning back, maybe thinking that you're making no progress. But you're about to start seeing new scenery. Things will be happening and it will make all the difference. <br><br>",

	"9 of Wands" => "The 9 of Wands is about stamina and vigilance and holding on for dear life when it seems like you're about to plunge a hundred stories to your death, maybe even crashing into a car or a baby on the way. It's about hanging in there when times are tough. Seeing things through to the end. Even when it seems things won't go your way. Don't give up the fight. Giving up means that success is sure to never come. Why would you settle for that? If you're trying to climb a mountain and you just sit down and hope that the top is just going to move closer, you won't make any progress at all. You're in for a dose of reality right in the face region if you do that. You've got to keep moving. You'll never get where you want to be unless you move towards it. Make it happen. One foot in front of the other. No goal is too far to reach, no matter what. The 9 of Wands says you have the energy to do it. <br><br>",

	"10 of Wands" => "The 10 of Wands talks about burden and toil. This card depicts an old truck loaded with heavy logs. It is a symbol of impending stress and a period of tribulation. Things will not be easy because it will seem like you won't get through it at times. But that is not the case. We can get through anything. The key is to figure out how to lighten the load. It's like trying to carry a bunch of wriggling toddlers. It would be easier just to drag them behind you. Find better ways to carry your stress or get someone to help you. Cut out anything that doesn't matter right now and lessen stress. Don't overdo things and take time to relax and recuperate. Sometimes the next rise is the end of the hard road and the beginning of smoother driving. There is a saying that most people give up right before they would have achieved success. The road may be difficult, but also think about all the times that were hard, all the difficult things you made it through before. You survived all that, right? This is no different. Life has a way of making it seem like what's happening now is the most awful thing, but really think about how many times you've thought that before. You did it then. You got through it. You're awesome. You can do it again. <br><br>",

	"Page of Wands" => "The Page of Wands depicts a small child with an umbrella out playing in the rain. She is playing with a kitten and enjoying herself, just being inquisitive and seeing the world through the eyes of wonder, as kids often do. The keywords here are creativity and ardor. What this card wants you to know is that you shouldn't be afraid to let your true self bleed through in your endeavors. The thing about kids is that they just create stuff without worrying about if it's going to suck or not. They just go and do what makes them happy. Everything is interesting to them. Don't ever hold yourself back from letting your full potential come through. Don't. Do what makes you happy and don't worry about what people will think. Do you want to be happy or do you want to be worried about what people think of you? It's only one or the other. <br><br>",

	"Knight of Wands" => "The Knight of Wands depicts a young hocky player. He is typically very passionate, hot-tempered, and cocky. He would be your Colin Farrell, a badboy who knows how to flaunt his sexiness. Unlike the Knight of Cups, his allure and charm does not come from sensitivity, but from unadultered confidence. He is brazen, and unafraid to do what makes him happy, what other people think be damned. This is the type of guy who seizes life by the horns and doesn't let go until it is tamed. The suit of wands is a fire suit, so this guy has lots of passion. His hot-headedness is apt to burn quite a few bridges also, but he doesn't care. If the Knight of Wands had a motto it would be 'Don't turn down your flame just because others can't handle the heat.' Be yourself and burn bright. <br><br>",

	"Queen of Wands" => "The Queen of Wands in the Darkana deck pictures a pole dancer in really high heels. She's the life of the party, the center of attention. The thing about her is that she knows she's alluring. She's self-assured. She knows how to use what she's got to her advantage and she knows there's nothing wrong with that. She walks a fine line between attention whore and someone who's alluring and classy. But she can still cross that line if she wants to because she's sure of herself and everyone else can piss off. There are many ways to influence people and persuade them and it's not her fault that people are easily persuaded by her charm and the hint of other things. It's a proven fact that attractive people have more opportunities. So be sexy and to hell with anyone who hates you for it. The only thing to watch out for with her is that she sometimes parties too much and shirks responsibilities. Don't be like the mindless celebrities who throw their lives away by being stupid. <br><br>",

	"King of Wands" => "The King of Wands is about passion and creativity. The King is the master of this domain. His keywords are INSPIRING and PASSIONATE. Imagine a superstar in any creative or innovative endeavor. A Picasso. A Steve Jobs. A Stephen King. What is the key to their success? They have passion about what they're doing. They let that fire burn, it fuels their dreams. They've also mastered overcoming doubt. There is a great deal of effort in this. Into just letting go and allowing your creativity to take over. It doesn't matter what people think. Where would the world be if these people were too scared of what people would think? But they're masters, you say. They're experts. Even those experts have critics. And they weren't always masters. But they did do one thing: they just went for it. They brought their special thing to the world. They understood that there were people who would enjoy it. There are 7 billion people in the world. Chances are high that what you have to offer will be wanted. Be like the King of Wands. Be passionate about your thing. <br><br>",

	"King of Wands Reversed" => "King of Wands Reversed. This guy. The motherfucking King, reversed. Of passion and creativity. He's normally full of inspiration and passion, but he seems to have lost his mojo. This guy is so full of creativity he could probably piss out a masterpiece, but lately lack of progress has demotivated and demoralized him. Which puts him into a cycle that's hard to break away from. Everything sucks right now, to him, so he wallows in pity and doesn't do anything of what makes him great, repeat ad nauseum. He's basically fucking himself by not enjoying himself and by not utilizing his many gifts and talents. He needs to stop being so serious, so scared of something not working out, and maybe also get laid. That might help. So basically what this person really needs to do is to just start doing the shit he loves and quit thinking about other bullshit. Who cares what people think? Hell, who cares what he thinks? He needs to quit being a Debbie Downer and start being a Debbie Awesomer. <br><br>",

	"Ace of Cups" => "The Ace of Cups, the ultimate cup, this card here portends a truckload of awesome in the relationship and emotion category. It's a damn flask on the card, which is about as awesome as it gets. There's always warm libation at hand whenever you have a flask, which is why it's on the Ace here. Something awesome is about to happen, and this could be something old is getting a kick in the ass to get it jump started again or something new and not yet jaded is about to arrive. Either way this cup is there for you in places where others are not or cannot be. It is with you always. That's what this card is trying to say. You can either keep all of that lovely whiskey for yourself or you can split it with others. It's up to you. <br><br>",

	"2 of Cups" => "The 2 of Cups talks about two people and their relationship together. The keywords are attraction and connection. The card shows a couple having drinks together, which is usually the start of something that has potential. Or it could also be a much needed rejuvenation between old friends, but usually it's about getting out with someone you're attracted to. There's really not much else to say about this card. Put yourself in a situation where this could happen. Go out with someone or put yourself in a scenario that allows this to happen. Be social. The important thing is to not get in your own way. Too many people rely on fate to just hand them over the things they want, thinking that it's just always going to be magical. But that is not the case. By doing things that increase your odds, whether that's going out and meeting people, improving yourself, getting new clothes or hitting the gym, it doesn't matter. Help yourself by putting your best self forward. Make improvements and don't stand in your own way. The more you improve, the better your odds will be. We obtain what we think we are worth. Increase your self worth and you will increase the quality of your mate. <br><br>",

	"3 of Cups" => "3 of Cups is most definitely a card of celebration, but it also depicts three people puking into a toilet because they've partied too much. Imagine one midget and how awesome that would be. Spend a day wrangling a roomful of them, though, and it probably wouldn't be much of a real circus. Either way, you would have fun doing it before you got to the end part anyways. Normal celebration ends up like this from time to time. Getting together with peers is a load of fun, especially if it ends up with someone having to sneak away from a new lover with an unfortunate face. So this really portends actually having a reason to celebrate, which might be a good sign when it comes to your issue at hand. <br><br>",

	"4 of Cups" => "The 4 of Cups depicts a guy at his desk and he's hunched over, dissatisfied with everything he's done so far. He is under the impression that everything he's done is complete crap. There are four trash cans full of crumpled paper. He can't seem to figure out just what he wants. This card is about apathy and not being satisfied with anything, whether it's what you're doing or what is being given to you. He's just like 'meh.' The first one happens when we are being too hard on ourselves. What are the odds that everything the guy in the picture did actually sucked? Pretty slim. So you have to give yourself more credit and quit being a jerk to yourself. It's okay to hold ourselves to a high standard, but realize that if nothing you do is to your satisfaction, you won't ever get anything done. It's okay to accept something we think is sub-par. It may be just the thing that others need to be inspired by. <br><br>",

	"5 of Cups" => "5 of Cups shows a person sitting on some stairs in despair. There are three broken wine glasses on the stairs, which this person is lamenting over. He doesn't even see the two that are still there, for focusing on the others. The keywords are loss and regret. This is about thinking on things you don't have or the things you lost instead of thinking about the things that are there or are right in front of you. When you reprogram your mind to think positively, you accomplish more than if you only think of the negatives. This is proven by science. Look up positive affirmations. If you say to yourself 'I don't want to be out of shape' your subconscious only processes 'I want to be out of shape'. So you think positively instead. 'I want to be fit.' Or 'I am fit.' The biggest obstacle is your own mind. This applies to all things. If you believe you're not a success yet, you'll do things that prove you're not a success. So believe you are successful and focus on the positive and magic will happen. <br><br>", 

	"6 of Cups" => "The 6 of Cups is a reminder of good times, happy memories, awesomeness. A lot of times this card represents things from our childhood, but basically anything from the past, since all memories are from the past. This card does one of two things: firstly, it portends that something from your past is going to drop by for a visit, whether that's an actual old friend, or whether it's a forgotten memory; secondly, it could also be reminding you not to forget about the good times you've had. Sometimes that is really easy to do when we slip into a routine or we start to take things for granted. How this relates to your situation is to remember the things that made things sort of magical or fun in the beginning. It's easy to get hung up on the crap and the way people can be, but try to focus on what you loved about the something in the beginning and get back to that. <br><br>",

	"7 of Cups" => "The 7 of Cups is about indecision from too many options. It shows 7 different jars, each containing something different. Some pickles, milk, other stuff. A fetus. It's like when you stand in front of the refrigerator staring. Everything looks good and nothing looks good. The issue stems from not knowing exactly what you want. Because you're afraid that if you make a decision it will be wrong and you'll lament it, wishing you'd have chosen from the others. If it's not an issue of passing opportunity, what's to say one can't choose one and try it out? If it doesn't work, you'll have learned something and you can come back and choose something else. This is the nature of trial and error. Innovation. No one great ever got everything right the first time. Edison is said to have tried 10,000 times before he got the light bulb right. He could have been a huge liar, but the point is still valid. What will be the worst thing that can happen from making a wrong decision? <br><br>",

	"8 of Cups" => "The 8 of Cups features a jeep and 8 canisters of fuel. It signifies going in search of something better. This card typically symbolizes the grass being greener on the other side. You'll never know for sure until you look. The keywords on it are 'seeking out' and 'moving on.' So this indicates that you really need to be testing this out to see if it's what's good for you. The cups suit is about emotion and relationships, so the actions and feelings in this card typically come from a deep want to go someplace else. Even if you don't want to, it's a sign that it might be a good idea to keep your options open OR it could also mean that someone else is thinking about moving on. Where most people fail is in thinking that the things they have are the best they're ever going to get. Or they wish that were the case so much that they ignore all evidence to the contrary. There is always a better job out there. There is always a better person out there. Always. Sometimes the grass isn't greener, but sometimes it actually is. <br><br>",

	"9 of Cups" => "The 9 of Cups features an ornate display of cups, arranged like a fountain where awesomeness flows out the top and falls down into all the other cups until they, too, are full of awesome. The fountain-like aspect sort of represents having the energy or contents of all the cups at once, all flowing together like a giant orgy of awesome. This card is typically considered the wish card. Most of the time people say that if this card appears in a reading, your wish will come true. The keywords on the card are fulfillment and pleasure. It's basically the card that comes right before the 10 of Cups, which portends being happy with everything you have. This card is like the moment before that, where you are given what you want. Like a surprise massage out of nowhere when you were just thinking about wanting one. So you can enjoy it. So the appearance of the 9 of Cups suggests that things will be falling into place and you will experience a period of extreme contentment and satisfaction. Your cups runneth over! <br><br>",

	"10 of Cups" => "The 10 of Cups typically symbolizes joy and family and happy times and stuff. This card depicts a family surrounding a dinner table filled with cups. Who knows what's in the cups, could be Sunny D, could be whiskey. Doesn't matter. It symbolizes a picture of an emotional situation at its best. It's the quintessential life for a lot of people, and even if you're not interested in the whole family thing, the spirit of the card is what's important. Having a sense of contentment and being able to look around you and be happy for all the things that you have. Being loved and being able to love freely without all the nonsense. It's about peacefulness and serenity. Not having much stress. Again, getting rid of the crap. It is about fulfillment. This bodes well where it comes to finances especially, as you'll be able to relax more and enjoy the finer things that life has to offer. You'll be able to spend more quality time doing things you love and being with people you care about. <br><br>",

	"Page of Cups" => "The Page of Cups is about affection and emotion. It shows a little kid, faceless, sitting in a high chair and drinking from a sippy cup. The idea is to show how all kids are completely full of emotion and joy and affection. There's just something about them. They're like animals, but even more potent. Very few people can resist the charm of a small child. The Page of Cups is very affectionate, and gives freely. What's more important, in this case, is that the Pages also represent new relationships. This page in particular. You are likely to meet someone new, whether that's a partner or just someone you will be interacting with. But you can significantly help fate/destiny/the Universe out here. By making room in your life to meet someone new, no matter what type of relationship it is. <br><br>",

	"Knight of Cups" => "The Knight of Cups depicts a savvy young fellow in a tuxedo holding a martini glass. The keywords are refined and sensitive. He's very charming, this knight. The cups refer to emotions and relationships, what you're holding inside. Emotions are like the liquid the cups are holding, while the relationships help define the shape the liquid takes on. So back to this knight here. The Knight of Cups is typically that overly romantic guy who can recite poetry and write love notes. He has a different type of charm. Like Manny on the show Modern Family. This guy typically gives more than he takes. He looks after your needs, or at least tries to make things easier on you. So be appreciative of all he does that's nice. The downside to this guy is that he may lack confidence, which makes it hard to know what his true intentions are. He is shy and prefers under-the-radar type of wooing. At his worst he can be very insecure, which leads to neediness and jealousy. But he is a nice guy at heart. Sometimes he may not realize he's being immature or a turn-off, and it will be tempting to spare his feelings because he is so sweet. What this guy needs more than anything is to hear the hard truth. He won't get hints. You have to be blunt and help him fix it. Everyone wins that way, and if this is you, don't lie to yourself. <br><br>",

	"Queen of Cups" => "The Queen of Cups is a sort of motherly, loving, charitable person. She is always smiling and always looking to help others. She would feed the whole neighborhood if she could. She would adopt a hundred stray pets if she could. She knows that life is too short to not say what you want to say, and she is always looking for a way to broker peace during confrontations. This person is warm and full of love and she knows that sharing this and being genuine is a great way to enhance the lives of others. She is the most selfless of the court cards. She is also overly accommodating at times. Like maybe this is the girl who is constantly finding herself giving massages to people who never return the favor. How is it she never gets to receive? This could be anybody, and the lesson here is that she (or he) needs to be more assertive and start making people earn what they are being given, otherwise they will continue taking advantage of it. She needn't change who she is, she just needs to be more discerning of who she gives her gifts to. <br><br>",

	"King of Cups" => "The King of Cups kind of indicates a situation of emotional self control. This is someone who is completely in control of their emotions, and can direct that energy almost effortlessly and perfectly tailored to the situation; unlike others who can be manipulative, vindictive, and emotionally controlling, this person has learned how to love him or herself so that none of that other crap is necessary. Imagine a child who throws tantrums or uses emotional blackmail to get his or her way. That's the exact type of this the King of Cups doesn't do. Because it's not necessary. This person isn't needy. Not like the people who text a hundred times because they didn't get an answer back within 10 seconds of the first one and can't fathom that somebody was engaged in something where they couldn't use the phone or that maybe the phone died. The King of Cups is reasonable. The King of Cups doesn't allow his emotions to control him, but recognizes that he can still be very emotional and passionate. <br><br>",

	"Ace of Pentacles" => "The Ace of Pentacles suggests something with the potential to bring in a little new prosperity to your life. This could be money or a sense of groundedness. This could be that a new project is going to start paying off or that you might catch a small windfall financially or that you will just experience a newfound sense of structure and you will more in tune with your surroundings. You might start seeing things a different way than before that enables you to walk through life differently. The image on the card shows a big pentacle like the Batman symbol over a nighttime city skyline. So think of it like that. The universe is shining the big symbol for you, so help is on the way. <br><br>",

	"2 of Pentacles" => "The 2 of Pentacles depicts a hamster in a wheel. Not going anywhere. Not because it's dead or anything, but because it's stuck in a wheel that doesn't go anywhere. This card is about juggling and stagnation, the same thing happening over and over and over. You can avoid stagnation by doing something differently than before. This sort of suggests that more of the same is coming for you in the short term, but it's important to realize that this is not forever. The thing with life is that you can't just rely on destiny. You have to forge your own destiny. There's another saying: 'The harder you work, the luckier you get.' Don't settle for anything less than success. You've got to try new things and keep trying them and keep persevering until it works. <br><br>",

	"3 of Pentacles" => "The 3 of Pentacles is about collaboration and work. This card usually infers that you should or will be working with others together in order to accomplish a common goal. This usually means that everyone will do their part and pull their weight. It also means that you will need to do the same, and that doesn't just mean doing your own particular part. It means that sometimes, for the sake of the whole project and the team, you may need to inspire others, or be a problem solver. There is no reason why you should do all the work, and simultaneously, it is unfair to expect others to do all the work as well, even if no one seems to mind. Work together. Be a team player. And assert yourself so that others are team players as well. And as with any team setting, you need to be able to get rid of anybody who causes more problems than they solve. <br><br>", 

	"4 of Pentacles" => "The 4 of Pentacles depicts four pentacles surrounded by chains. The fours are typically about stability, like how a table with four legs is more stable than one with three. The four of pentacles is about financial stability, or at least paying attention to it. The keywords on this card are greed and control. Now, the idea is to gain control over your finances, and this is typically personified by the Rider-Waite miser hanging on to his money for dear life. Penny-pinching, or at least exercising more responsibility. It only becomes greed when you take this to extremes and start hoarding. The key to financial autonomy lies in either living below your means or increasing your means. Which one sounds more appealing? <br><br>",

	"5 of Pentacles" => "The 5 of Pentacles shows a wheelchair. It signifies poverty, despair, sometimes sickness. It is very likely that one or more of those things leads to despair, so of course this card is apt. The wheelchair is a very apt description of a situation in which it becomes important to take happiness into one's own hands. Everyone forgets that happiness is a choice. Every day there are accidents and unfortunate scenarios where people end up in wheelchairs. This can be very demoralizing. People can fall into deep depression. But is it really the end of the world? There are plenty of people in wheelchairs who have traveled all over the world. They do downhill skiing, scuba diving, racing. Some people in wheelchairs still go surfing and skydiving. The only crutch is the mind. So how can you turn your situation into something better? Even bedridden people find purpose, whether it's through writing a book, playing music, or solving some other problem. So what is your problem and how are you letting it screw you over unnecessarily? <br><br>",

	"6 of Pentacles" => "The 6 of Pentacles shows a BINGO card with 6 pentacles as the blotters being used to cover the numbers. This card stands for generosity and charity and helping people and giving them stuff (or being helped and getting stuff). Most of the time this refers to money. That's what the pentacles represent - money, workplace, earth, food. The idea behind this card deals with karma, and it kind of talks about being in a place where things aren't so bad economically where you can be a little more generous with your money. And this giving can be done however you want, there's no damn formula to follow, so whether it's just buying locally to help people in your area or donating to Caskets for Kids, it doesn't matter. It could even be just donating blood or giving a minute of time to someone you don't like being around. The idea here is that of karma, so by giving something while you're in a good position to do so, you'll be setting yourself up for the future in times where you can't give. Theoretically it should all come around to you again. It also implies that someone might be acting charitably towards you, which could also just mean the world in general and not some specific person. In other words, a windfall of sorts. <br><br>",

	"7 of Pentacles" => "The 7 of Pentacles shows a person hiking up a mountainside. 7 pentacles are lined up along the way, so if the person wants to get them all, they just need to hike to go get them. And this dude is collecting these things like a boss. The keywords are perseverance and reward. It's a very straightforward card. Effort in = reward. If the hiker gives up, he doesn't get the reward. He gets nothing. This applies to your case, to all cases really. There is nothing one cannot accomplish through determination and hard work. Let's look at this hiker again. If the hiker decides to just sit down, he will never get anything. The rewards are there for the taking, you just have to get up and go get them. So you have to go for it. The rewards are waiting. <br><br>",
	 
	"8 of Pentacles" => "The 8 of Pentacles depicts a legendary guitarist. The 8 pentacles are all notes on a grand scale behind the legend on the guitar. The keywords are diligence and innovation. This card is about being a master, but one of your own design. It's about working hard to master something and then utilizing those skills and talents to innovate and become legendary. It is scientific consensus that it takes 10,000 hours of practice to master something. Anything. Regardless of talent. So you could be the most uncoordinated person of all time and after 10,000 hours of piano lessons, you would be a master. Fact. Remember this. It has nothing to do with talent. Whatever you want to be good at, work hard and you will achieve it. No matter what. This is a guarantee. So do you want to have fun or do you want to master something? Trick question. The thing you master should be fun, otherwise what's the point? <br><br>",

	"9 of Pentacles" => "The 9 of Pentacles depicts a beautiful dame with a parasol in a flowing robe. The keywords are affluence and refinement. This card comes near the end of the pentacles numbered cards, and indicates a time of luxury, or at least being able to relax a bit and enjoy things on a higher level than before. Imagine a spa, or a sanctuary. Some place you can go to get away from everything. You will be able to do that. Not only will you be able to afford that, but you will be able to have the time to do so, which is another luxury. Some people cannot find the time to get away. You will be just fine. And even if money is tight right now, you can always find a way to enjoy your time and splurge on yourself, to relax and be merry. <br><br>",

	"10 of Pentacles" => "In the 10 of Pentacles, we see an awesome family standing near a large Christmas tree that doesn't suck. This implies security and success, a sense of relaxing and not having to stress over a lot of different crap. You may experience a financial windfall that enables you to deal with things much easier, or it could be the culmination of a lot of hard work and sacrifice on your part, which leads to it. Either way, be grateful for everything that comes your way. This also means being aware of opportunities to manifest such a state. The pentacles is also about being grounded and realistic, not just about money. But the two go hand in hand. Contemplate each decision and opportunity and scrutinize it, just like a savvy entrepreneur would. Don't be afraid to take risks - risks are not the enemy. Wild risk is. So just minimize your risk with prudence. And because this is about enjoying the fruits of everything, take advantage of any extra time by spending it with friends and family. It will help you recharge and you can bring that energy back into your career, which perpetuates that state of security. See how that works? <br><br>",

	"Page of Pentacles" => "The Page of Pentacles usually portends new opportunities for making money. New projects, whatever. The keywords on this are practical and prosperous. It shows a little kid behind a lemonade stand. Imagine that for a second. By the time we've grown up, we are so conditioned to think that we need to get a real job or do everything the same way everyone else does that we forget how a small idea and a little drive can make things happen. Little kids do this all the time. They get funding from their parents or they save up for cups and a bunch of lemonade mix. They put out a table and slap a homemade sign up. Then they sell the product. If kids can do this on their own, why aren't more adults doing similar stuff? The answer is fear. They don't think it'll work. Or they get so entrenched in a certain life that they can't disrupt it even long enough to try something new. So do yourself a favor. Keep an eye open for opportunities. Create your own opportunities. Go for it. <br><br>",

	"Knight of Pentacles" => "The Knight of Pentacles shows a young badboy on a motorcycle. The keywords are 'stubborn' and 'obsessive.' Think of the young entrepreneur here. He doesn't know everything there is to know about business. He knows enough, though, and the rest of his success will stem from confidence. The stubborn aspect is a hard perseverance. Persistence accomplishes what many other things cannot. Obsession is usually seen as a dangerous thing. But like all things, it is something that can be useful when harnessed properly. As long as it's tempered. Like anger. Anger can be a powerful motivator for change. It only becomes negative when it is harnessed improperly or when someone allows it to control them. Be bold. Be confident. Do not wait until you know everything because that will never happen. Do not be afraid of making mistakes, because we all make mistakes. <br><br>",

	"Queen of Pentacles" => "The Queen of Pentacles can balance work and play seamlessly so that nothing is neglected. She is able to thrive in any type of economy, always finding a way to be financially secure. She thinks about how work and entertainment will all play out in the long term. She makes things look easy, and that's because to her, they are easy. She knows how to delegate and simplify, the two keys to relieving stress. One of her favorite equations is work in = results, or even better: work in < results. So if you look at your situation and you're seeing this: work in > results, you need to look at what you're doing and make some adjustments. The Queen of Pentacles knows how to get maximum results with the littlest effort. If this is not you, you may be focused on the wrong aspect of things, or getting stressed over things that really aren't a big factor in the bigger picture. In fact, this is a great time to mention the Pareto Principle. It basically states that 20% of the work you do yields 80% of the results. That's not much, 20%. So where people go wrong is that 80% of the things they're doing don't really do much, so if you can figure out that 20% that really matters, you'll eliminate 80% of your stress. Does that make sense? You should look that up, Pareto's Principle. This concept applies to just about everything. Reduce your stress by doing what really matters. <br><br>",

	"King of Pentacles" => "The King of Pentacles depicts a businessman sitting in a chair. He's wearing a large, super awesome watch on his hand with a big pentacle on it. Why? Because he does what he wants. The keywords on the card are Articulation and Analysis. Kings are people who have mastered their chosen area of expertise, and being that these are pentacles, we have here a man who is adept at business, finances. He is very practical, grounded. He pays his bills on time. He knows where his money is coming from and where it's going and he weighs each decision. He does risk analysis. He takes risks, but they're calculated. A good real-world example is the entrepreneurial type, someone who didn't use his money to pay off debts and just buy things. He bought things that brought him more money so he wasn't always living paycheck to paycheck. <br><br>"
	);

$intro = "Hey, XXXXX. Let's see what we can do for a quick reading. I'm doing three cards today instead of the usual two. Here are the cards that came up for you: <br><br>";

$outro =  "Let me know if you have any questions, and if you would like to leave a tip, you can just paypal tarot@inappropriatetarot.com. Had to add the **** in there because FB is not letting me put spaces between paragraphs today.";

echo $intro . "*************************";

$rand_card1 = array_rand($general_cards);
$rand_card2 = array_rand($general_cards);
$rand_card3 = array_rand($general_cards);
$value1 = $general_cards[$rand_card1];
$value2 = $general_cards[$rand_card2];
$value3 = $general_cards[$rand_card3];

	echo $value1 . "*************************";
	echo $value2 . "*************************";
	echo $value3 . "*************************";
	
echo $outro;

?>